"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { listProducts, type Product } from "../../lib/catalogue";
import { customersApi, partyApi, type PartyRow, moneyText } from "../../lib/parties";
import { labels, previewDocument, saveDocument, type BusinessDocument, type DocumentInput, type DocumentKind } from "../../lib/business-documents";
import styles from "../parties/parties.module.css";

type Line = { productId: string; quantity: string; unitPrice: string; discountType: "NONE" | "PERCENT" | "AMOUNT"; discountValue: string; sourceInvoiceLineId?: string; sourceDocumentLineId?: string };
const today = () => new Date().toISOString().slice(0,10);
export function BusinessDocumentForm({ kind, id, initial }: { kind: DocumentKind; id?: string; initial?: BusinessDocument }) {
  const router = useRouter(); const label = labels[kind]; const supplier = label.party === "supplier";
  const [parties, setParties] = useState<PartyRow[]>([]); const [products, setProducts] = useState<Product[]>([]);
  const [partyId, setPartyId] = useState(initial?.customerId ?? initial?.supplierId ?? ""); const [placeState,setPlaceState] = useState(initial?.placeOfSupplyState ?? ""); const [placeCode,setPlaceCode] = useState(initial?.placeOfSupplyStateCode ?? "");
  const [documentDate,setDocumentDate] = useState(initial?.documentDate ?? today()); const [validUntil,setValidUntil] = useState(initial?.validUntil ?? ""); const [dueDate,setDueDate] = useState(initial?.dueDate ?? ""); const [priceMode,setPriceMode] = useState<"EXCLUSIVE"|"INCLUSIVE">(initial?.priceMode ?? "EXCLUSIVE"); const [supplierInvoiceNumber,setSupplierInvoiceNumber] = useState(initial?.supplierInvoiceNumber ?? ""); const [reason,setReason] = useState(initial?.reason ?? ""); const [notes,setNotes] = useState(initial?.notes ?? ""); const [terms,setTerms] = useState(initial?.terms ?? "");
  const [lines,setLines] = useState<Line[]>(initial?.lines.length ? initial.lines.map((line)=>({ productId: line.productId ?? "", quantity: line.quantity.replace(/\.?0+$/,"") || "0", unitPrice: line.unitPrice, discountType: line.discountType, discountValue: line.discountValue })) : [{ productId: "", quantity: "1", unitPrice: "0", discountType: "NONE", discountValue: "0" }]);
  const [preview,setPreview] = useState<BusinessDocument | null>(initial ?? null); const [error,setError] = useState(""); const [saving,setSaving] = useState(false); const seq = useRef(0);
  useEffect(()=>{ const q = new URLSearchParams({ pageSize: "100", status: "active" }); (supplier ? partyApi("suppliers").list(q) : customersApi.list(q)).then((r)=>setParties(r.items)); listProducts(q.toString()).then((r)=>setProducts(r.items)); }, [supplier]);
  useEffect(()=>{ if (!partyId && parties[0]) { setPartyId(parties[0].id); setPlaceState(parties[0].state); setPlaceCode(parties[0].stateCode); } }, [parties, partyId]);
  const payload = (): DocumentInput => ({ ...(supplier ? { supplierId: partyId } : { customerId: partyId }), supplierInvoiceNumber: supplierInvoiceNumber || undefined, placeOfSupplyState: placeState, placeOfSupplyStateCode: placeCode, documentDate, dueDate: dueDate || undefined, validUntil: validUntil || undefined, priceMode, reason: reason || undefined, notes, terms, lines: lines.filter((line)=>line.productId).map((line)=>({ ...line, discountValue: line.discountValue || "0" })) });
  useEffect(()=>{ if (!partyId || !placeState || !placeCode || !lines.some((line)=>line.productId)) return; const current = ++seq.current; const controller = new AbortController(); previewDocument(kind, payload(), controller.signal).then((next)=>{ if (current === seq.current) setPreview(next); }).catch(()=>undefined); return () => controller.abort(); }, [kind, partyId, placeState, placeCode, documentDate, dueDate, validUntil, priceMode, supplierInvoiceNumber, reason, notes, terms, lines]);
  const chooseProduct = (index: number, productId: string) => setLines((rows)=>rows.map((line,i)=>{ if (i !== index) return line; const item = products.find((p)=>p.id===productId); return { ...line, productId, unitPrice: item?.salePrice ?? line.unitPrice }; }));
  const save = async () => { setSaving(true); setError(""); try { const saved = await saveDocument(kind, payload(), id); router.push(`/${kind}/${saved.id}?saved=1`); } catch(e) { setError(e instanceof Error ? e.message : "Could not save document"); } finally { setSaving(false); } };
  return <main className={styles.page}><div className={styles.heading}><div><p className={styles.eyebrow}>{supplier ? "Purchases" : "Sales"}</p><h1>{id ? "Edit draft" : "Create " + label.title.slice(0,-1)}</h1><p>Totals come from the server preview and are recalculated on save.</p></div><Link className={styles.secondary} href={`/${kind}`}>All documents</Link></div>{error && <section className={styles.panel} role="alert">{error}</section>}
    <section className={styles.panel}><div className={styles.grid}><label>{supplier ? "Supplier" : "Customer"}<select value={partyId} onChange={(e)=>{ const row = parties.find((p)=>p.id===e.target.value); setPartyId(e.target.value); if (row) { setPlaceState(row.state); setPlaceCode(row.stateCode); } }}><option value="">Choose party</option>{parties.map((party)=><option key={party.id} value={party.id}>{party.displayName}</option>)}</select></label><label>Document date<input type="date" value={documentDate} onChange={(e)=>setDocumentDate(e.target.value)} /></label>{kind === "quotations" && <label>Valid until<input type="date" value={validUntil} onChange={(e)=>setValidUntil(e.target.value)} /></label>}<label>Due date<input type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)} /></label>{kind === "purchase-bills" && <label>Supplier bill number<input value={supplierInvoiceNumber} onChange={(e)=>setSupplierInvoiceNumber(e.target.value)} /></label>}<label>Price mode<select value={priceMode} onChange={(e)=>setPriceMode(e.target.value as "EXCLUSIVE"|"INCLUSIVE")}><option value="EXCLUSIVE">Tax exclusive</option><option value="INCLUSIVE">Tax inclusive</option></select></label><label>Place of supply<input value={placeState} onChange={(e)=>setPlaceState(e.target.value)} /></label><label>GST state code<input value={placeCode} onChange={(e)=>setPlaceCode(e.target.value)} /></label></div></section>
    <section className={styles.panel}><h2>Line items</h2>{lines.map((line,index)=><div className={styles.grid} key={index}><label className={styles.full}>Product or service<select value={line.productId} onChange={(e)=>chooseProduct(index,e.target.value)}><option value="">Choose item</option>{products.map((p)=><option key={p.id} value={p.id}>{p.productCode} - {p.name}</option>)}</select></label><label>Quantity<input value={line.quantity} inputMode="decimal" onChange={(e)=>setLines((rows)=>rows.map((r,i)=>i===index?{...r,quantity:e.target.value}:r))} /></label><label>Unit price<input value={line.unitPrice} inputMode="decimal" onChange={(e)=>setLines((rows)=>rows.map((r,i)=>i===index?{...r,unitPrice:e.target.value}:r))} /></label><label>Discount<select value={line.discountType} onChange={(e)=>setLines((rows)=>rows.map((r,i)=>i===index?{...r,discountType:e.target.value as Line["discountType"]}:r))}><option value="NONE">None</option><option value="PERCENT">Percent</option><option value="AMOUNT">Amount</option></select></label><label>Discount value<input value={line.discountValue} inputMode="decimal" onChange={(e)=>setLines((rows)=>rows.map((r,i)=>i===index?{...r,discountValue:e.target.value}:r))} /></label></div>)}<div className={styles.actions}><button className={styles.secondary} onClick={()=>setLines((rows)=>[...rows,{ productId:"", quantity:"1", unitPrice:"0", discountType:"NONE", discountValue:"0" }])}>Add line</button></div></section>
    <section className={styles.panel}><h2>Totals</h2>{preview ? <dl className={styles.details}><dt>Subtotal</dt><dd>{moneyText(preview.subtotal)}</dd><dt>Discount</dt><dd>{moneyText(preview.discountTotal)}</dd><dt>Taxable</dt><dd>{moneyText(preview.taxableTotal)}</dd><dt>CGST</dt><dd>{moneyText(preview.cgstTotal)}</dd><dt>SGST</dt><dd>{moneyText(preview.sgstTotal)}</dd><dt>IGST</dt><dd>{moneyText(preview.igstTotal)}</dd><dt>Grand total</dt><dd>{moneyText(preview.grandTotal)}</dd></dl> : <p className={styles.muted}>Choose a party and item to preview totals.</p>}</section>
    <section className={styles.panel}><div className={styles.grid}><label>Reason<textarea value={reason} onChange={(e)=>setReason(e.target.value)} /></label><label>Notes<textarea value={notes} onChange={(e)=>setNotes(e.target.value)} /></label><label>Terms<textarea value={terms} onChange={(e)=>setTerms(e.target.value)} /></label></div><div className={styles.actions}><button className={styles.button} disabled={saving} onClick={save}>{saving ? "Saving" : "Save draft"}</button><Link className={styles.secondary} href={`/${kind}`}>Cancel</Link></div></section>
  </main>;
}
