"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { LoadState, Modal, useLoad } from "../catalogue/common";
import { actionDocument, convertDocument, convertDocumentToInvoice, deleteDocument, getDocument, labels, type BusinessDocument, type DocumentKind } from "../../lib/business-documents";
import { moneyText } from "../../lib/parties";
import styles from "../parties/parties.module.css";

function actionFor(kind: DocumentKind) { return kind === "quotations" || kind === "delivery-challans" ? "issue" : kind === "sales-orders" || kind === "purchase-orders" ? "confirm" : "finalize"; }
export function BusinessDocumentDetail({ kind, id }: { kind: DocumentKind; id: string }) {
  const router = useRouter(); const params = useSearchParams(); const { data, error, retry } = useLoad(kind + id + params.toString(), (signal)=>getDocument(kind,id,signal)); const [action,setAction] = useState<"move"|"cancel"|"delete"|"convert"|"invoice"|null>(null); const [reason,setReason] = useState(""); const [actionError,setActionError] = useState(""); const label = labels[kind];
  if (!data || error) return <main className={styles.page}><LoadState error={error} retry={retry} /></main>;
  const conversionTarget = kind === "quotations" ? { slug: "sales-order", path: "sales-orders", label: "Convert to sales order" } : kind === "sales-orders" ? { slug: "delivery-challan", path: "delivery-challans", label: "Convert to delivery challan" } : kind === "purchase-orders" ? { slug: "purchase-bill", path: "purchase-bills", label: "Convert to purchase bill" } : null;
  const invoiceConvertible = kind === "quotations" || kind === "sales-orders" || kind === "delivery-challans";
  const run = async () => { setActionError(""); try { if (action === "move") await actionDocument(kind,id,actionFor(kind)); else if (action === "cancel") await actionDocument(kind,id,"cancel",reason); else if (action === "convert" && conversionTarget) { const target = await convertDocument(kind,id,conversionTarget.slug); router.push("/" + conversionTarget.path + "/" + target.id); return; } else if (action === "invoice") { const invoice = await convertDocumentToInvoice(kind,id); router.push("/invoices/" + invoice.id + "/edit"); return; } else { await deleteDocument(kind,id); router.replace("/" + kind); return; } setAction(null); retry(); } catch(e) { setActionError(e instanceof Error ? e.message : "Action failed"); } };
  return <main className={styles.page}><div className={styles.heading}><div><p className={styles.eyebrow}>{label.title}</p><h1>{data.documentNumber ?? "Draft"}</h1><p>{data.partyNameSnapshot} - {data.documentDate}</p></div><div className={styles.actions}><Link className={styles.secondary} href={`/${kind}`}>All documents</Link>{data.status === "DRAFT" && <Link className={styles.secondary} href={`/${kind}/${id}/edit`}>Edit</Link>}<Link className={styles.button} href={`/${kind}/${id}/print`}>Print</Link></div></div>
    <section className={styles.panel}><span className={data.status === "CANCELLED" ? styles.inactive + " " + styles.status : styles.status}>{data.status}</span><dl className={styles.details}><dt>Financial year</dt><dd>{data.financialYear}</dd><dt>Place of supply</dt><dd>{data.placeOfSupplyState} ({data.placeOfSupplyStateCode})</dd><dt>{label.party === "customer" ? "Customer" : "Supplier"}</dt><dd>{data.partyNameSnapshot}{data.partyGstinSnapshot ? "\nGSTIN " + data.partyGstinSnapshot : ""}</dd><dt>Business</dt><dd>{data.businessNameSnapshot}{data.businessGstinSnapshot ? "\nGSTIN " + data.businessGstinSnapshot : ""}</dd>{data.supplierInvoiceNumber && <><dt>Supplier bill</dt><dd>{data.supplierInvoiceNumber}</dd></>}{data.cancellationReason && <><dt>Cancellation reason</dt><dd>{data.cancellationReason}</dd></>}</dl></section><DocumentTable document={data} /><section className={styles.panel}><h2>Totals</h2><dl className={styles.details}><dt>Subtotal</dt><dd>{moneyText(data.subtotal)}</dd><dt>Discount</dt><dd>{moneyText(data.discountTotal)}</dd><dt>Taxable</dt><dd>{moneyText(data.taxableTotal)}</dd><dt>CGST</dt><dd>{moneyText(data.cgstTotal)}</dd><dt>SGST</dt><dd>{moneyText(data.sgstTotal)}</dd><dt>IGST</dt><dd>{moneyText(data.igstTotal)}</dd><dt>Grand total</dt><dd>{moneyText(data.grandTotal)}</dd></dl></section><section className={styles.panel}><div className={styles.actions}>{data.status === "DRAFT" && <><button className={styles.button} onClick={()=>setAction("move")}>{label.action}</button><button className={styles.secondary} onClick={()=>setAction("delete")}>Delete draft</button></>}{data.status !== "DRAFT" && data.status !== "CANCELLED" && <>{conversionTarget && <button className={styles.secondary} onClick={()=>setAction("convert")}>{conversionTarget.label}</button>}{invoiceConvertible && <button className={styles.secondary} onClick={()=>setAction("invoice")}>Convert to invoice draft</button>}<button className={styles.secondary} onClick={()=>setAction("cancel")}>Cancel document</button></>}</div></section>
    {action && <Modal title={action === "move" ? label.action : action === "cancel" ? "Cancel document" : action === "convert" ? "Convert document" : action === "invoice" ? "Convert to invoice draft" : "Delete draft"} close={()=>setAction(null)}><p>{action === "move" ? "This assigns the server document number and freezes commercial snapshots where this lifecycle requires it." : action === "cancel" ? "This preserves the document and reverses Phase 7 stock impact where applicable." : action === "convert" ? "This creates a new draft target document from stored commercial inputs and recalculates totals on the server." : action === "invoice" ? "This creates a new unnumbered invoice draft through the Phase 6 invoice engine. No stock is deducted until invoice finalization." : "Draft documents have no issued number and may be removed."}</p>{action === "cancel" && <label>Cancellation reason<textarea value={reason} onChange={(e)=>setReason(e.target.value)} /></label>}{actionError && <p role="alert">{actionError}</p>}<div className={styles.actions}><button className={styles.button} onClick={run}>{action === "move" ? label.action : action === "cancel" ? "Cancel document" : action === "convert" ? "Create draft" : action === "invoice" ? "Create invoice draft" : "Delete draft"}</button><button className={styles.secondary} onClick={()=>setAction(null)}>Keep document</button></div></Modal>}
  </main>;
}
export function DocumentTable({ document }: { document: BusinessDocument }) { return <section className={styles.panel}><h2>Line items</h2><table className={styles.table}><thead><tr><th>Item</th><th>HSN/SAC</th><th>Qty</th><th>Rate</th><th>Discount</th><th>Tax</th><th>Total</th></tr></thead><tbody>{document.lines.map((line)=><tr key={line.lineNumber}><td data-label="Item">{line.productNameSnapshot}<small>{line.productCodeSnapshot}</small></td><td data-label="HSN/SAC">{line.hsnSacCodeSnapshot ?? ""}</td><td data-label="Qty">{line.quantity} {line.unitSnapshot}</td><td data-label="Rate">{moneyText(line.unitPrice)}</td><td data-label="Discount">{moneyText(line.discountAmount)}</td><td data-label="Tax">{moneyText(line.taxAmount)}<small>GST {line.gstRate}%</small></td><td data-label="Total">{moneyText(line.lineTotal)}</td></tr>)}</tbody></table></section>; }
