import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service.js';
import { Prisma } from '../generated/prisma/client.js';
import type { SafeUser } from '../users/user.select.js';
import { dateOnly, financialYear, money, parseDateOnly } from '../invoices/invoice-calculator.js';
import { ownerScope, requireOwner } from '../parties/party.data.js';
import type { AccountEntryQuery, AccountQuery, ExpenseCategoryDto, ExpenseDto, ExpenseQuery, MoneyAccountDto, PayableQuery, PaymentDto, PaymentQuery, ReasonDto, ReceivableQuery, TransferDto } from './finance.dto.js';

const D = Prisma.Decimal;
const ZERO = new D(0);
type Tx = Prisma.TransactionClient;
const retry = async <T>(fn: () => Promise<T>) => { for (let i = 0; ; i++) { try { return await fn(); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2034' && i < 2) continue; throw e; } } };
const clean = (v?: string) => v?.trim() || null;
const page = (q: { page: number; pageSize: number }) => ({ skip: (q.page - 1) * q.pageSize, take: q.pageSize });

@Injectable()
export class FinanceService {
  constructor(private readonly db: DatabaseService) {}

  private async nextAccountCode(tx: Tx, businessId: string) {
    const row = await tx.business.update({ where: { id: businessId }, data: { nextAccountNumber: { increment: 1 } }, select: { nextAccountNumber: true } });
    return 'ACC-' + String(row.nextAccountNumber).padStart(6, '0');
  }
  private async nextNumber(tx: Tx, businessId: string, type: 'CUSTOMER_RECEIPT'|'SUPPLIER_PAYMENT'|'EXPENSE'|'TRANSFER', fy: string) {
    const row = await tx.financeSequence.upsert({ where: { businessId_type_financialYear: { businessId, type, financialYear: fy } }, create: { businessId, type, financialYear: fy, nextNumber: 1 }, update: { nextNumber: { increment: 1 } }, select: { nextNumber: true } });
    const prefix = type === 'CUSTOMER_RECEIPT' ? 'RCPT' : type === 'SUPPLIER_PAYMENT' ? 'PAY' : type === 'EXPENSE' ? 'EXP' : 'TRF';
    return { sequenceNumber: row.nextNumber, number: `${prefix}/${fy}/${String(row.nextNumber).padStart(6, '0')}` };
  }
  private async changeBalance(tx: Tx, businessId: string, accountId: string, direction: 'CREDIT'|'DEBIT', amount: Prisma.Decimal, entry: Omit<Prisma.MoneyAccountEntryUncheckedCreateInput, 'businessId'|'accountId'|'direction'|'amount'|'balanceBefore'|'balanceAfter'>) {
    const account = await tx.moneyAccount.findFirst({ where: { businessId, id: accountId } });
    if (!account || !account.isActive) throw new BadRequestException('Active account not found');
    const before = account.currentBalance;
    const after = direction === 'CREDIT' ? money(before.plus(amount)) : money(before.minus(amount));
    const update = await tx.moneyAccount.updateMany({ where: { businessId, id: accountId, currentBalance: before }, data: { currentBalance: after } });
    if (update.count !== 1) throw new ConflictException('Account balance changed. Please retry.');
    await tx.moneyAccountEntry.create({ data: { businessId, accountId, direction, amount, balanceBefore: before, balanceAfter: after, ...entry } });
    return after;
  }
  private ser(row: Record<string, unknown>) { return Object.fromEntries(Object.entries(row).map(([k,v]) => [k, v instanceof D ? v.toFixed(2) : v instanceof Date ? dateOnly(v) : v])); }
  private accountSer(row: Record<string, unknown>) { return this.ser(row); }
  private paymentSer(row: any) { return { ...this.ser(row), allocations: row.allocations?.map((a: any) => this.ser(a)) ?? [] }; }
  private expenseSer(row: any) { return this.ser(row); }

  async createAccount(user: SafeUser, dto: MoneyAccountDto) { return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const opening = money(dto.openingBalance ?? '0'); const row = await tx.moneyAccount.create({ data: { businessId: scope.businessId, accountCode: await this.nextAccountCode(tx, scope.businessId), name: dto.name, type: dto.type, bankName: clean(dto.bankName), accountNumberLast4: clean(dto.accountNumberLast4), ifsc: clean(dto.ifsc), upiId: clean(dto.upiId), openingBalance: opening, currentBalance: opening, isActive: dto.isActive ?? true, createdById: user.id } }); if (!opening.eq(0)) await tx.moneyAccountEntry.create({ data: { businessId: scope.businessId, accountId: row.id, type: 'OPENING_BALANCE', direction: opening.gte(0) ? 'CREDIT' : 'DEBIT', amount: opening.abs(), balanceBefore: ZERO, balanceAfter: opening, description: 'Opening account balance', createdById: user.id } }); return this.accountSer(row); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  async accounts(user: SafeUser, q: AccountQuery) { const scope = ownerScope(user); const where: Prisma.MoneyAccountWhereInput = { ...scope, ...(q.status === 'all' ? {} : { isActive: q.status === 'active' }), ...(q.type ? { type: q.type as any } : {}), ...(q.search ? { OR: [{ accountCode: { contains: q.search, mode: 'insensitive' } }, { name: { contains: q.search, mode: 'insensitive' } }, { bankName: { contains: q.search, mode: 'insensitive' } }] } : {}) }; const [rows,total] = await this.db.$transaction([this.db.moneyAccount.findMany({ where, ...page(q), orderBy: [{ isActive: 'desc' }, { name: 'asc' }, { id: 'asc' }] }), this.db.moneyAccount.count({ where })]); return { items: rows.map(r => this.accountSer(r)), page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }
  async account(user: SafeUser, id: string) { const row = await this.db.moneyAccount.findFirst({ where: { ...ownerScope(user), id } }); if (!row) throw new NotFoundException('Account not found'); return this.accountSer(row); }
  async updateAccount(user: SafeUser, id: string, dto: MoneyAccountDto) { return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const row = await tx.moneyAccount.findFirst({ where: { ...scope, id } }); if (!row) throw new NotFoundException('Account not found'); const updated = await tx.moneyAccount.update({ where: { id }, data: { name: dto.name, type: dto.type, bankName: clean(dto.bankName), accountNumberLast4: clean(dto.accountNumberLast4), ifsc: clean(dto.ifsc), upiId: clean(dto.upiId), isActive: dto.isActive ?? row.isActive } }); return this.accountSer(updated); }); }
  async deactivateAccount(user: SafeUser, id: string) { await this.updateAccount(user, id, { ...(await this.account(user,id) as any), isActive: false }); return { ok: true }; }
  async accountEntries(user: SafeUser, id: string, q: AccountEntryQuery) { const scope = ownerScope(user); await this.account(user, id); const where: Prisma.MoneyAccountEntryWhereInput = { ...scope, accountId: id, ...(q.type ? { type: q.type as any } : {}), ...(q.direction ? { direction: q.direction as any } : {}), ...(q.dateFrom || q.dateTo ? { createdAt: { ...(q.dateFrom ? { gte: parseDateOnly(q.dateFrom) } : {}), ...(q.dateTo ? { lte: parseDateOnly(q.dateTo) } : {}) } } : {}) }; const [rows,total] = await this.db.$transaction([this.db.moneyAccountEntry.findMany({ where, ...page(q), orderBy: [{ createdAt: 'desc' }, { id: 'desc' }] }), this.db.moneyAccountEntry.count({ where })]); return { items: rows.map(r => ({ date: dateOnly(r.createdAt), reference: r.referenceType ? `${r.referenceType}:${r.referenceId ?? ''}` : null, description: r.description, credit: r.direction === 'CREDIT' ? r.amount.toFixed(2) : '0.00', debit: r.direction === 'DEBIT' ? r.amount.toFixed(2) : '0.00', balanceAfter: r.balanceAfter.toFixed(2), type: r.type })), page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }

  private paymentData(dto: PaymentDto) { const amount = money(dto.amount); if (!amount.gt(0)) throw new BadRequestException('Amount must be greater than zero'); if (dto.type === 'CUSTOMER_RECEIPT' && (!dto.customerId || dto.supplierId)) throw new BadRequestException('Customer receipt requires customerId only'); if (dto.type === 'SUPPLIER_PAYMENT' && (!dto.supplierId || dto.customerId)) throw new BadRequestException('Supplier payment requires supplierId only'); const total = dto.allocations.reduce((a,l) => a.plus(money(l.amount)), ZERO); if (!total.eq(amount)) throw new BadRequestException('Allocation total must equal payment amount'); for (const l of dto.allocations) if ((l.invoiceId ? 1 : 0) + (l.documentId ? 1 : 0) !== 1) throw new BadRequestException('Each allocation must target one document'); return { amount, financialYear: financialYear(dto.paymentDate), paymentDate: parseDateOnly(dto.paymentDate) }; }
  async createPayment(user: SafeUser, dto: PaymentDto) { const parsed = this.paymentData(dto); return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); await this.ensurePaymentRefs(tx, scope.businessId, dto); const row = await tx.payment.create({ data: { businessId: scope.businessId, type: dto.type, customerId: dto.customerId ?? null, supplierId: dto.supplierId ?? null, accountId: dto.accountId, paymentDate: parsed.paymentDate, financialYear: parsed.financialYear, method: dto.method, referenceNumber: clean(dto.referenceNumber), amount: parsed.amount, notes: clean(dto.notes), createdById: user.id, allocations: { create: dto.allocations.map(a => ({ businessId: scope.businessId, invoiceId: a.invoiceId ?? null, documentId: a.documentId ?? null, amount: money(a.amount) })) } }, include: { allocations: true } }); return this.paymentSer(row); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  async payments(user: SafeUser, q: PaymentQuery) { const scope = ownerScope(user); const where: Prisma.PaymentWhereInput = { ...scope, ...(q.type ? { type: q.type as any } : {}), ...(q.status ? { status: q.status as any } : {}), ...(q.method ? { method: q.method as any } : {}), ...(q.customerId ? { customerId: q.customerId } : {}), ...(q.supplierId ? { supplierId: q.supplierId } : {}), ...(q.accountId ? { accountId: q.accountId } : {}), ...(q.search ? { OR: [{ paymentNumber: { contains: q.search, mode: 'insensitive' } }, { referenceNumber: { contains: q.search, mode: 'insensitive' } }] } : {}) }; const [rows,total] = await this.db.$transaction([this.db.payment.findMany({ where, include: { allocations: true }, ...page(q), orderBy: [{ [q.sortBy]: q.sortOrder }, { id: 'asc' }] }), this.db.payment.count({ where })]); return { items: rows.map(r => this.paymentSer(r)), page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }
  async payment(user: SafeUser, id: string) { const row = await this.db.payment.findFirst({ where: { ...ownerScope(user), id }, include: { allocations: true } }); if (!row) throw new NotFoundException('Payment not found'); return this.paymentSer(row); }
  async updatePayment(user: SafeUser, id: string, dto: PaymentDto) { const parsed = this.paymentData(dto); return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const existing = await tx.payment.findFirst({ where: { ...scope, id }, include: { allocations: true } }); if (!existing) throw new NotFoundException('Payment not found'); if (existing.status !== 'DRAFT') throw new BadRequestException('Only draft payments can be edited'); await this.ensurePaymentRefs(tx, scope.businessId, dto); await tx.paymentAllocation.deleteMany({ where: { businessId: scope.businessId, paymentId: id } }); const row = await tx.payment.update({ where: { id }, data: { type: dto.type, customerId: dto.customerId ?? null, supplierId: dto.supplierId ?? null, accountId: dto.accountId, paymentDate: parsed.paymentDate, financialYear: parsed.financialYear, method: dto.method, referenceNumber: clean(dto.referenceNumber), amount: parsed.amount, notes: clean(dto.notes), allocations: { create: dto.allocations.map(a => ({ businessId: scope.businessId, invoiceId: a.invoiceId ?? null, documentId: a.documentId ?? null, amount: money(a.amount) })) } }, include: { allocations: true } }); return this.paymentSer(row); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  async deletePayment(user: SafeUser, id: string) { return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const row = await tx.payment.findFirst({ where: { ...scope, id } }); if (!row) throw new NotFoundException('Payment not found'); if (row.status !== 'DRAFT') throw new BadRequestException('Only draft payments can be deleted'); await tx.payment.delete({ where: { id } }); return { ok: true }; }); }
  async postPayment(user: SafeUser, id: string) { return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const p = await tx.payment.findFirst({ where: { ...scope, id }, include: { allocations: true } }); if (!p) throw new NotFoundException('Payment not found'); if (p.status !== 'DRAFT') throw new BadRequestException('Only draft payments can be posted'); await this.validateOutstanding(tx, scope.businessId, p.type, p.allocations, p.id); const n = await this.nextNumber(tx, scope.businessId, p.type, p.financialYear); await this.changeBalance(tx, scope.businessId, p.accountId, p.type === 'CUSTOMER_RECEIPT' ? 'CREDIT' : 'DEBIT', p.amount, { type: p.type, paymentId: p.id, referenceType: 'PAYMENT', referenceId: n.number, description: p.type === 'CUSTOMER_RECEIPT' ? 'Customer receipt posted' : 'Supplier payment posted', createdById: user.id }); const ok = await tx.payment.updateMany({ where: { businessId: scope.businessId, id, status: 'DRAFT', paymentNumber: null }, data: { status: 'POSTED', paymentNumber: n.number, sequenceNumber: n.sequenceNumber, postedAt: new Date(), postedById: user.id } }); if (ok.count !== 1) throw new ConflictException('Payment was already posted'); return this.paymentSer(await tx.payment.findFirstOrThrow({ where: { ...scope, id }, include: { allocations: true } })); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  async reversePayment(user: SafeUser, id: string, dto: ReasonDto) { return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const p = await tx.payment.findFirst({ where: { ...scope, id }, include: { allocations: true } }); if (!p) throw new NotFoundException('Payment not found'); if (p.status !== 'POSTED') throw new BadRequestException('Only posted payments can be reversed'); await this.changeBalance(tx, scope.businessId, p.accountId, p.type === 'CUSTOMER_RECEIPT' ? 'DEBIT' : 'CREDIT', p.amount, { type: 'PAYMENT_REVERSAL', paymentId: p.id, referenceType: 'PAYMENT', referenceId: p.paymentNumber, description: dto.reason, createdById: user.id }); const ok = await tx.payment.updateMany({ where: { businessId: scope.businessId, id, status: 'POSTED', reversedAt: null }, data: { status: 'REVERSED', reversedAt: new Date(), reversedById: user.id, reversalReason: dto.reason } }); if (ok.count !== 1) throw new ConflictException('Payment was already reversed'); return this.paymentSer(await tx.payment.findFirstOrThrow({ where: { ...scope, id }, include: { allocations: true } })); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  private async ensurePaymentRefs(tx: Tx, businessId: string, dto: PaymentDto) { if (!await tx.moneyAccount.findFirst({ where: { businessId, id: dto.accountId, isActive: true } })) throw new BadRequestException('Active account not found'); if (dto.customerId && !await tx.customer.findFirst({ where: { businessId, id: dto.customerId, isActive: true } })) throw new BadRequestException('Active customer not found'); if (dto.supplierId && !await tx.supplier.findFirst({ where: { businessId, id: dto.supplierId, isActive: true } })) throw new BadRequestException('Active supplier not found'); }
  private async validateOutstanding(tx: Tx, businessId: string, type: string, allocations: { invoiceId: string|null; documentId: string|null; amount: Prisma.Decimal; paymentId: string }[], paymentId: string) { for (const a of allocations) { if (type === 'CUSTOMER_RECEIPT') { if (!a.invoiceId || a.documentId) throw new BadRequestException('Customer receipts allocate to invoices only'); const invoice = await tx.invoice.findFirst({ where: { businessId, id: a.invoiceId, status: 'FINALIZED' }, select: { grandTotal: true } }); if (!invoice) throw new BadRequestException('Finalized invoice not found'); const paid = await tx.paymentAllocation.aggregate({ where: { businessId, invoiceId: a.invoiceId, paymentId: { not: paymentId }, payment: { status: 'POSTED', type: 'CUSTOMER_RECEIPT' } }, _sum: { amount: true } }); if ((paid._sum.amount ?? ZERO).plus(a.amount).gt(invoice.grandTotal)) throw new BadRequestException('Allocation exceeds invoice outstanding'); } else { if (!a.documentId || a.invoiceId) throw new BadRequestException('Supplier payments allocate to purchase bills only'); const bill = await tx.businessDocument.findFirst({ where: { businessId, id: a.documentId, documentType: 'PURCHASE_BILL', status: 'FINALIZED' }, select: { grandTotal: true } }); if (!bill) throw new BadRequestException('Finalized purchase bill not found'); const paid = await tx.paymentAllocation.aggregate({ where: { businessId, documentId: a.documentId, paymentId: { not: paymentId }, payment: { status: 'POSTED', type: 'SUPPLIER_PAYMENT' } }, _sum: { amount: true } }); if ((paid._sum.amount ?? ZERO).plus(a.amount).gt(bill.grandTotal)) throw new BadRequestException('Allocation exceeds purchase bill payable'); } } }

  async createExpenseCategory(user: SafeUser, dto: ExpenseCategoryDto) { try { return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const row = await tx.expenseCategory.create({ data: { businessId: scope.businessId, name: dto.name, nameKey: dto.name.toLocaleLowerCase('en-IN'), description: clean(dto.description), isActive: dto.isActive ?? true, createdById: user.id } }); return this.ser(row); }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException('Expense category already exists'); throw e; } }
  async expenseCategories(user: SafeUser, q: AccountQuery) { const scope = ownerScope(user); const where: Prisma.ExpenseCategoryWhereInput = { ...scope, ...(q.status === 'all' ? {} : { isActive: q.status === 'active' }), ...(q.search ? { name: { contains: q.search, mode: 'insensitive' } } : {}) }; const [rows,total] = await this.db.$transaction([this.db.expenseCategory.findMany({ where, ...page(q), orderBy: [{ isActive: 'desc' }, { name: 'asc' }] }), this.db.expenseCategory.count({ where })]); return { items: rows.map(r => this.ser(r)), page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }
  async updateExpenseCategory(user: SafeUser, id: string, dto: ExpenseCategoryDto) { return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const existing = await tx.expenseCategory.findFirst({ where: { ...scope, id } }); if (!existing) throw new NotFoundException('Expense category not found'); const row = await tx.expenseCategory.update({ where: { id }, data: { name: dto.name, nameKey: dto.name.toLocaleLowerCase('en-IN'), description: clean(dto.description), isActive: dto.isActive ?? existing.isActive } }); return this.ser(row); }); }
  async deactivateExpenseCategory(user: SafeUser, id: string) { const current = await this.db.expenseCategory.findFirst({ where: { ...ownerScope(user), id } }); if (!current) throw new NotFoundException('Expense category not found'); await this.updateExpenseCategory(user, id, { name: current.name, description: current.description ?? undefined, isActive: false }); return { ok: true }; }
  private expenseData(dto: ExpenseDto) { const amount = money(dto.amount); if (!amount.gt(0)) throw new BadRequestException('Amount must be greater than zero'); return { amount, financialYear: financialYear(dto.expenseDate), expenseDate: parseDateOnly(dto.expenseDate) }; }
  async createExpense(user: SafeUser, dto: ExpenseDto) { const parsed = this.expenseData(dto); return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); await this.ensureExpenseRefs(tx, scope.businessId, dto); const row = await tx.expense.create({ data: { businessId: scope.businessId, categoryId: dto.categoryId, accountId: dto.accountId, supplierId: dto.supplierId ?? null, expenseDate: parsed.expenseDate, financialYear: parsed.financialYear, description: dto.description, amount: parsed.amount, method: dto.method, referenceNumber: clean(dto.referenceNumber), notes: clean(dto.notes), createdById: user.id } }); return this.expenseSer(row); }); }
  async expenses(user: SafeUser, q: ExpenseQuery) { const scope = ownerScope(user); const where: Prisma.ExpenseWhereInput = { ...scope, ...(q.status ? { status: q.status as any } : {}), ...(q.categoryId ? { categoryId: q.categoryId } : {}), ...(q.accountId ? { accountId: q.accountId } : {}), ...(q.supplierId ? { supplierId: q.supplierId } : {}), ...(q.search ? { OR: [{ expenseNumber: { contains: q.search, mode: 'insensitive' } }, { description: { contains: q.search, mode: 'insensitive' } }, { referenceNumber: { contains: q.search, mode: 'insensitive' } }] } : {}) }; const [rows,total] = await this.db.$transaction([this.db.expense.findMany({ where, ...page(q), orderBy: [{ [q.sortBy]: q.sortOrder }, { id: 'asc' }] }), this.db.expense.count({ where })]); return { items: rows.map(r => this.expenseSer(r)), page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }
  async expense(user: SafeUser, id: string) { const row = await this.db.expense.findFirst({ where: { ...ownerScope(user), id } }); if (!row) throw new NotFoundException('Expense not found'); return this.expenseSer(row); }
  async updateExpense(user: SafeUser, id: string, dto: ExpenseDto) { const parsed = this.expenseData(dto); return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const ex = await tx.expense.findFirst({ where: { ...scope, id } }); if (!ex) throw new NotFoundException('Expense not found'); if (ex.status !== 'DRAFT') throw new BadRequestException('Only draft expenses can be edited'); await this.ensureExpenseRefs(tx, scope.businessId, dto); const row = await tx.expense.update({ where: { id }, data: { categoryId: dto.categoryId, accountId: dto.accountId, supplierId: dto.supplierId ?? null, expenseDate: parsed.expenseDate, financialYear: parsed.financialYear, description: dto.description, amount: parsed.amount, method: dto.method, referenceNumber: clean(dto.referenceNumber), notes: clean(dto.notes) } }); return this.expenseSer(row); }); }
  async deleteExpense(user: SafeUser, id: string) { return this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const ex = await tx.expense.findFirst({ where: { ...scope, id } }); if (!ex) throw new NotFoundException('Expense not found'); if (ex.status !== 'DRAFT') throw new BadRequestException('Only draft expenses can be deleted'); await tx.expense.delete({ where: { id } }); return { ok: true }; }); }
  async postExpense(user: SafeUser, id: string) { return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const ex = await tx.expense.findFirst({ where: { ...scope, id } }); if (!ex) throw new NotFoundException('Expense not found'); if (ex.status !== 'DRAFT') throw new BadRequestException('Only draft expenses can be posted'); const n = await this.nextNumber(tx, scope.businessId, 'EXPENSE', ex.financialYear); await this.changeBalance(tx, scope.businessId, ex.accountId, 'DEBIT', ex.amount, { type: 'EXPENSE', expenseId: ex.id, referenceType: 'EXPENSE', referenceId: n.number, description: ex.description, createdById: user.id }); await tx.expense.updateMany({ where: { businessId: scope.businessId, id, status: 'DRAFT', expenseNumber: null }, data: { status: 'POSTED', expenseNumber: n.number, sequenceNumber: n.sequenceNumber, postedAt: new Date(), postedById: user.id } }); return this.expenseSer(await tx.expense.findFirstOrThrow({ where: { ...scope, id } })); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  async cancelExpense(user: SafeUser, id: string, dto: ReasonDto) { return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const ex = await tx.expense.findFirst({ where: { ...scope, id } }); if (!ex) throw new NotFoundException('Expense not found'); if (ex.status !== 'POSTED') throw new BadRequestException('Only posted expenses can be cancelled'); await this.changeBalance(tx, scope.businessId, ex.accountId, 'CREDIT', ex.amount, { type: 'EXPENSE_REVERSAL', expenseId: ex.id, referenceType: 'EXPENSE', referenceId: ex.expenseNumber, description: dto.reason, createdById: user.id }); await tx.expense.updateMany({ where: { businessId: scope.businessId, id, status: 'POSTED', cancelledAt: null }, data: { status: 'CANCELLED', cancelledAt: new Date(), cancelledById: user.id, cancellationReason: dto.reason } }); return this.expenseSer(await tx.expense.findFirstOrThrow({ where: { ...scope, id } })); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }
  private async ensureExpenseRefs(tx: Tx, businessId: string, dto: ExpenseDto) { if (!await tx.moneyAccount.findFirst({ where: { businessId, id: dto.accountId, isActive: true } })) throw new BadRequestException('Active account not found'); if (!await tx.expenseCategory.findFirst({ where: { businessId, id: dto.categoryId, isActive: true } })) throw new BadRequestException('Active expense category not found'); if (dto.supplierId && !await tx.supplier.findFirst({ where: { businessId, id: dto.supplierId, isActive: true } })) throw new BadRequestException('Active supplier not found'); }

  async createTransfer(user: SafeUser, dto: TransferDto) { const amount = money(dto.amount); if (!amount.gt(0)) throw new BadRequestException('Amount must be greater than zero'); if (dto.fromAccountId === dto.toAccountId) throw new BadRequestException('Transfer accounts must differ'); return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const fy = financialYear(dto.transferDate); const n = await this.nextNumber(tx, scope.businessId, 'TRANSFER', fy); const row = await tx.accountTransfer.create({ data: { businessId: scope.businessId, transferNumber: n.number, sequenceNumber: n.sequenceNumber, financialYear: fy, fromAccountId: dto.fromAccountId, toAccountId: dto.toAccountId, transferDate: parseDateOnly(dto.transferDate), amount, referenceNumber: clean(dto.referenceNumber), notes: clean(dto.notes), createdById: user.id } }); await this.changeBalance(tx, scope.businessId, dto.fromAccountId, 'DEBIT', amount, { type: 'TRANSFER_OUT', transferId: row.id, referenceType: 'TRANSFER', referenceId: n.number, description: 'Internal transfer out', createdById: user.id }); await this.changeBalance(tx, scope.businessId, dto.toAccountId, 'CREDIT', amount, { type: 'TRANSFER_IN', transferId: row.id, referenceType: 'TRANSFER', referenceId: n.number, description: 'Internal transfer in', createdById: user.id }); return this.ser(row); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }

  async transfers(user: SafeUser, q: PaymentQuery) { const scope = ownerScope(user); const where: Prisma.AccountTransferWhereInput = { ...scope, ...(q.status ? { status: q.status as any } : {}), ...(q.accountId ? { OR: [{ fromAccountId: q.accountId }, { toAccountId: q.accountId }] } : {}), ...(q.search ? { OR: [{ transferNumber: { contains: q.search, mode: 'insensitive' } }, { referenceNumber: { contains: q.search, mode: 'insensitive' } }] } : {}) }; const [rows,total] = await this.db.$transaction([this.db.accountTransfer.findMany({ where, ...page(q), orderBy: [{ createdAt: 'desc' }, { id: 'asc' }], include: { fromAccount: { select: { id: true, accountCode: true, name: true, type: true } }, toAccount: { select: { id: true, accountCode: true, name: true, type: true } } } }), this.db.accountTransfer.count({ where })]); return { items: rows.map((r: any) => this.ser(r)), page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }
  async transfer(user: SafeUser, id: string) { const row = await this.db.accountTransfer.findFirst({ where: { ...ownerScope(user), id }, include: { fromAccount: { select: { id: true, accountCode: true, name: true, type: true } }, toAccount: { select: { id: true, accountCode: true, name: true, type: true } } } }); if (!row) throw new NotFoundException('Transfer not found'); return this.ser(row as any); }
  async reverseTransfer(user: SafeUser, id: string, dto: ReasonDto) { return retry(() => this.db.$transaction(async tx => { const scope = await requireOwner(tx, user); const tr = await tx.accountTransfer.findFirst({ where: { ...scope, id } }); if (!tr) throw new NotFoundException('Transfer not found'); if (tr.status !== 'POSTED') throw new BadRequestException('Only posted transfers can be reversed'); await this.changeBalance(tx, scope.businessId, tr.fromAccountId, 'CREDIT', tr.amount, { type: 'TRANSFER_REVERSAL', transferId: tr.id, referenceType: 'TRANSFER', referenceId: tr.transferNumber, description: dto.reason, createdById: user.id }); await this.changeBalance(tx, scope.businessId, tr.toAccountId, 'DEBIT', tr.amount, { type: 'TRANSFER_REVERSAL', transferId: tr.id, referenceType: 'TRANSFER', referenceId: tr.transferNumber, description: dto.reason, createdById: user.id }); await tx.accountTransfer.updateMany({ where: { businessId: scope.businessId, id, status: 'POSTED', reversedAt: null }, data: { status: 'REVERSED', reversedAt: new Date(), reversedById: user.id, reversalReason: dto.reason } }); return this.ser(await tx.accountTransfer.findFirstOrThrow({ where: { ...scope, id } })); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable })); }

  private settlementStatus(paid: Prisma.Decimal, total: Prisma.Decimal) { const outstanding = money(total.minus(paid)); return { outstanding, paymentStatus: paid.eq(0) ? 'UNPAID' : outstanding.gt(0) ? 'PARTIAL' : 'PAID' }; }
  private isOverdue(dueDate: Date | null | undefined, outstanding: Prisma.Decimal) { return !!dueDate && outstanding.gt(0) && dueDate.getTime() < Date.now(); }
  private async filteredSettlements<T>(q: { page: number; pageSize: number; status?: string }, fetch: (skip: number, take: number) => Promise<T[]>, map: (row: T) => any) { const take = Math.max(100, q.pageSize * 4); const start = (q.page - 1) * q.pageSize; const items: any[] = []; let total = 0; let skip = 0; for (;;) { const rows = await fetch(skip, take); if (!rows.length) break; for (const row of rows) { const item = map(row); const matched = !q.status || q.status === item.paymentStatus || (q.status === 'OVERDUE' && item.daysOverdue > 0); if (matched) { if (total >= start && items.length < q.pageSize) items.push(item); total++; } } if (rows.length < take) break; skip += take; } return { items, page: q.page, pageSize: q.pageSize, total, totalPages: Math.ceil(total/q.pageSize) }; }
  async receivables(user: SafeUser, q: ReceivableQuery) { const scope = ownerScope(user); const where: Prisma.InvoiceWhereInput = { ...scope, status: 'FINALIZED', ...(q.customerId ? { customerId: q.customerId } : {}), ...(q.search ? { OR: [{ invoiceNumber: { contains: q.search, mode: 'insensitive' } }, { customerNameSnapshot: { contains: q.search, mode: 'insensitive' } }] } : {}) }; return this.filteredSettlements(q, (skip, take) => this.db.invoice.findMany({ where, skip, take, orderBy: [{ invoiceDate: 'desc' }, { id: 'asc' }], include: { paymentAllocations: { where: { payment: { status: 'POSTED', type: 'CUSTOMER_RECEIPT' } } } } }), (r: any) => { const paid = r.paymentAllocations.reduce((a: Prisma.Decimal,b: { amount: Prisma.Decimal }) => a.plus(b.amount), ZERO); const { outstanding, paymentStatus } = this.settlementStatus(paid, r.grandTotal); return { invoice: { id: r.id, invoiceNumber: r.invoiceNumber }, customer: { id: r.customerId, name: r.customerNameSnapshot }, invoiceDate: dateOnly(r.invoiceDate), dueDate: r.dueDate ? dateOnly(r.dueDate) : null, grandTotal: r.grandTotal.toFixed(2), paidAmount: paid.toFixed(2), outstanding: outstanding.toFixed(2), paymentStatus, daysOverdue: this.isOverdue(r.dueDate, outstanding) ? Math.floor((Date.now()-r.dueDate.getTime())/86400000) : 0 }; }); }
  async payables(user: SafeUser, q: PayableQuery) { const scope = ownerScope(user); const where: Prisma.BusinessDocumentWhereInput = { ...scope, documentType: 'PURCHASE_BILL', status: 'FINALIZED', ...(q.supplierId ? { supplierId: q.supplierId } : {}), ...(q.search ? { OR: [{ documentNumber: { contains: q.search, mode: 'insensitive' } }, { partyNameSnapshot: { contains: q.search, mode: 'insensitive' } }] } : {}) }; return this.filteredSettlements(q, (skip, take) => this.db.businessDocument.findMany({ where, skip, take, orderBy: [{ documentDate: 'desc' }, { id: 'asc' }], include: { paymentAllocations: { where: { payment: { status: 'POSTED', type: 'SUPPLIER_PAYMENT' } } } } }), (r: any) => { const paid = r.paymentAllocations.reduce((a: Prisma.Decimal,b: { amount: Prisma.Decimal }) => a.plus(b.amount), ZERO); const { outstanding, paymentStatus } = this.settlementStatus(paid, r.grandTotal); return { purchaseBill: { id: r.id, documentNumber: r.documentNumber }, supplier: { id: r.supplierId, name: r.partyNameSnapshot }, billDate: dateOnly(r.documentDate), dueDate: r.dueDate ? dateOnly(r.dueDate) : null, grandTotal: r.grandTotal.toFixed(2), paidAmount: paid.toFixed(2), outstanding: outstanding.toFixed(2), paymentStatus, daysOverdue: this.isOverdue(r.dueDate, outstanding) ? Math.floor((Date.now()-r.dueDate.getTime())/86400000) : 0 }; }); }
}
