import { z } from "zod";
import { api } from "./api";
import { paged } from "./catalogue";

const money = z.string().regex(/^\d+(\.\d{2})$/);
const qty = z.string().regex(/^\d+(\.\d{3})$/);
const paymentHistorySchema = z.object({ paymentId: z.string().optional(), paymentNumber: z.string().nullable().optional(), paymentDate: z.string().nullable().optional(), amount: money, method: z.string().optional(), status: z.string().optional(), account: z.object({ id: z.string(), accountCode: z.string(), name: z.string(), type: z.string() }).nullable().optional() });
const settlementSchema = z.object({ paymentStatus: z.enum(["UNAVAILABLE","UNPAID","PARTIAL","PAID"]), paidAmount: money, outstanding: money, paymentHistory: z.array(paymentHistorySchema) }).optional();
export type DocumentKind = "quotations" | "sales-orders" | "delivery-challans" | "sales-returns" | "purchase-orders" | "purchase-bills" | "purchase-returns";
export const labels: Record<DocumentKind, { title: string; party: "customer" | "supplier"; action: string }> = {
  quotations: { title: "Quotations", party: "customer", action: "Issue quotation" },
  "sales-orders": { title: "Sales Orders", party: "customer", action: "Confirm order" },
  "delivery-challans": { title: "Delivery Challans", party: "customer", action: "Issue challan" },
  "sales-returns": { title: "Sales Returns", party: "customer", action: "Finalize return" },
  "purchase-orders": { title: "Purchase Orders", party: "supplier", action: "Confirm order" },
  "purchase-bills": { title: "Purchase Bills", party: "supplier", action: "Finalize bill" },
  "purchase-returns": { title: "Purchase Returns", party: "supplier", action: "Finalize return" },
};
export const documentLineInputSchema = z.object({ productId: z.string().uuid(), sourceInvoiceLineId: z.string().uuid().optional(), sourceDocumentLineId: z.string().uuid().optional(), quantity: z.string(), unitPrice: z.string(), discountType: z.enum(["NONE", "PERCENT", "AMOUNT"]), discountValue: z.string().optional() });
export const documentInputSchema = z.object({ customerId: z.string().uuid().optional(), supplierId: z.string().uuid().optional(), sourceInvoiceId: z.string().uuid().optional(), sourceDocumentId: z.string().uuid().optional(), supplierInvoiceNumber: z.string().optional(), placeOfSupplyState: z.string(), placeOfSupplyStateCode: z.string(), documentDate: z.string(), dueDate: z.string().optional(), validUntil: z.string().optional(), priceMode: z.enum(["EXCLUSIVE", "INCLUSIVE"]), reason: z.string().optional(), notes: z.string().optional(), terms: z.string().optional(), lines: z.array(documentLineInputSchema).min(1) });
export type DocumentInput = z.infer<typeof documentInputSchema>;
const lineSchema = z.object({ id: z.string().nullable().optional(), productId: z.string().nullable(), lineNumber: z.number(), productCodeSnapshot: z.string().nullable(), productNameSnapshot: z.string(), productTypeSnapshot: z.enum(["PRODUCT", "SERVICE"]), hsnSacCodeSnapshot: z.string().nullable(), unitSnapshot: z.string(), quantity: qty, unitPrice: money, priceMode: z.enum(["EXCLUSIVE", "INCLUSIVE"]), discountType: z.enum(["NONE", "PERCENT", "AMOUNT"]), discountValue: money, discountAmount: money, grossAmount: money, taxableAmount: money, gstRate: money, cgstRate: money, cgstAmount: money, sgstRate: money, sgstAmount: money, igstRate: money, igstAmount: money, taxAmount: money, lineTotal: money });
export const documentSchema = z.object({ id: z.string().nullable(), documentType: z.string(), status: z.string(), documentNumber: z.string().nullable(), financialYear: z.string(), documentDate: z.string(), dueDate: z.string().nullable().optional(), validUntil: z.string().nullable().optional(), customerId: z.string().nullable().optional(), supplierId: z.string().nullable().optional(), supplierInvoiceNumber: z.string().nullable().optional(), partyNameSnapshot: z.string(), partyCodeSnapshot: z.string().nullable(), partyGstinSnapshot: z.string().nullable(), partyAddressLine1: z.string(), partyCity: z.string(), partyState: z.string(), partyPincode: z.string(), businessNameSnapshot: z.string(), businessGstinSnapshot: z.string().nullable(), businessAddressLine1: z.string(), businessCity: z.string(), businessState: z.string(), businessPincode: z.string(), placeOfSupplyState: z.string(), placeOfSupplyStateCode: z.string(), priceMode: z.enum(["EXCLUSIVE", "INCLUSIVE"]), reason: z.string().nullable().optional(), cancellationReason: z.string().nullable().optional(), notes: z.string().nullable().optional(), terms: z.string().nullable().optional(), subtotal: money, discountTotal: money, taxableTotal: money, cgstTotal: money, sgstTotal: money, igstTotal: money, taxTotal: money, roundOff: money, grandTotal: money, settlement: settlementSchema, lines: z.array(lineSchema) });
export type BusinessDocument = z.infer<typeof documentSchema>;
const rowSchema = z.object({ id: z.string(), documentType: z.string(), status: z.string(), documentNumber: z.string().nullable(), documentDate: z.string(), financialYear: z.string(), partyNameSnapshot: z.string(), grandTotal: money, supplierInvoiceNumber: z.string().nullable().optional() });
export async function listDocuments(kind: DocumentKind, q: URLSearchParams, signal?: AbortSignal) { return paged(rowSchema).parse(await api("/" + kind + "?" + q, { signal })); }
export async function getDocument(kind: DocumentKind, id: string, signal?: AbortSignal) { return documentSchema.parse((await api("/" + kind + "/" + id, { signal }) as { profile: unknown }).profile); }
export async function previewDocument(kind: DocumentKind, input: DocumentInput, signal?: AbortSignal) { return documentSchema.parse(await api("/" + kind + "/preview", { method: "POST", body: JSON.stringify(input), signal })); }
export async function saveDocument(kind: DocumentKind, input: DocumentInput, id?: string) { return documentSchema.parse((await api("/" + kind + (id ? "/" + id : ""), { method: id ? "PATCH" : "POST", body: JSON.stringify(input) }) as { profile: unknown }).profile); }
export async function actionDocument(kind: DocumentKind, id: string, action: string, reason?: string) { return documentSchema.parse((await api("/" + kind + "/" + id + "/" + action, { method: "POST", body: action === "cancel" ? JSON.stringify({ reason }) : undefined }) as { profile: unknown }).profile); }
export async function convertDocument(kind: DocumentKind, id: string, target: string) { return documentSchema.parse((await api("/" + kind + "/" + id + "/convert/" + target, { method: "POST" }) as { profile: unknown }).profile); }
export async function convertDocumentToInvoice(kind: DocumentKind, id: string) { return z.object({ id: z.string(), status: z.string(), invoiceNumber: z.string().nullable() }).passthrough().parse((await api("/" + kind + "/" + id + "/convert-to-invoice", { method: "POST" }) as { profile: unknown }).profile); }
export async function deleteDocument(kind: DocumentKind, id: string) { return api("/" + kind + "/" + id, { method: "DELETE" }); }
