import { z } from "zod";
import { api } from "./api";

const money = z.string();
const list = <T extends z.ZodTypeAny>(item: T) => z.object({ items: z.array(item), page: z.number(), pageSize: z.number(), total: z.number(), totalPages: z.number() });
export const accountSchema = z.object({ id: z.string(), accountCode: z.string(), name: z.string(), type: z.string(), currentBalance: money, openingBalance: money, isActive: z.boolean(), bankName: z.string().nullable().optional(), accountNumberLast4: z.string().nullable().optional(), ifsc: z.string().nullable().optional(), upiId: z.string().nullable().optional(), createdAt: z.string().optional() }).passthrough();
export const paymentSchema = z.object({ id: z.string(), paymentNumber: z.string().nullable().optional(), type: z.string(), status: z.string(), paymentDate: z.string(), amount: money, method: z.string(), allocations: z.array(z.object({ id: z.string(), invoiceId: z.string().nullable().optional(), documentId: z.string().nullable().optional(), amount: money }).passthrough()).optional(), referenceNumber: z.string().nullable().optional(), reversalReason: z.string().nullable().optional() }).passthrough();
export const expenseCategorySchema = z.object({ id: z.string(), name: z.string(), description: z.string().nullable().optional(), isActive: z.boolean() }).passthrough();
export const expenseSchema = z.object({ id: z.string(), expenseNumber: z.string().nullable().optional(), description: z.string(), status: z.string(), expenseDate: z.string(), amount: money, method: z.string(), categoryId: z.string().optional(), accountId: z.string().optional(), supplierId: z.string().nullable().optional(), referenceNumber: z.string().nullable().optional(), notes: z.string().nullable().optional(), cancellationReason: z.string().nullable().optional() }).passthrough();
export const transferSchema = z.object({ id: z.string(), transferNumber: z.string(), status: z.string(), transferDate: z.string(), amount: money, referenceNumber: z.string().nullable().optional(), notes: z.string().nullable().optional(), reversalReason: z.string().nullable().optional(), fromAccount: accountSchema.pick({ id: true, accountCode: true, name: true, type: true }).optional(), toAccount: accountSchema.pick({ id: true, accountCode: true, name: true, type: true }).optional() }).passthrough();
export const settlementSchema = z.object({ paymentStatus: z.string(), grandTotal: money, paidAmount: money, outstanding: money }).passthrough();
export type Account = z.infer<typeof accountSchema>; export type Payment = z.infer<typeof paymentSchema>; export type ExpenseCategory = z.infer<typeof expenseCategorySchema>; export type Expense = z.infer<typeof expenseSchema>; export type Transfer = z.infer<typeof transferSchema>;
const body = (value: unknown) => JSON.stringify(value);
export const listAccounts = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/accounts?${q}`, { signal }).then(list(accountSchema).parse);
export const getAccount = (id: string, signal?: AbortSignal) => api<unknown>(`/accounts/${id}`, { signal }).then(z.object({ profile: accountSchema }).parse).then(r=>r.profile);
export const createAccount = (data: unknown) => api<{profile: Account}>("/accounts", { method: "POST", body: body(data) }).then(z.object({ profile: accountSchema }).parse);
export const updateAccount = (id: string, data: unknown) => api<{profile: Account}>(`/accounts/${id}`, { method: "PATCH", body: body(data) }).then(z.object({ profile: accountSchema }).parse);
export const deactivateAccount = (id: string) => api<unknown>(`/accounts/${id}`, { method: "DELETE" });
export const accountTransactions = (id: string, q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/accounts/${id}/transactions?${q}`, { signal }).then(z.object({ items: z.array(z.object({ date: z.string(), description: z.string().nullable(), credit: money, debit: money, balanceAfter: money, type: z.string() }).passthrough()), page: z.number(), pageSize: z.number(), total: z.number(), totalPages: z.number() }).parse);
export const listPayments = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/payments?${q}`, { signal }).then(list(paymentSchema).parse);
export const getPayment = (id: string, signal?: AbortSignal) => api<unknown>("/payments/" + id, { signal }).then(z.object({ profile: paymentSchema }).parse).then((r) => r.profile);
export const createPayment = (data: unknown) => api<{profile: Payment}>("/payments", { method: "POST", body: body(data) }).then(z.object({ profile: paymentSchema }).parse);
export const postPayment = (id: string) => api<{profile: Payment}>(`/payments/${id}/post`, { method: "POST" }).then(z.object({ profile: paymentSchema }).parse);
export const reversePayment = (id: string, reason: string) => api<{profile: Payment}>(`/payments/${id}/reverse`, { method: "POST", body: body({ reason }) }).then(z.object({ profile: paymentSchema }).parse);
export const listExpenseCategories = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/expense-categories?${q}`, { signal }).then(list(expenseCategorySchema).parse);
export const createExpenseCategory = (data: unknown) => api<{profile: ExpenseCategory}>("/expense-categories", { method: "POST", body: body(data) }).then(z.object({ profile: expenseCategorySchema }).parse);
export const listExpenses = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/expenses?${q}`, { signal }).then(list(expenseSchema).parse);
export const getExpense = (id: string, signal?: AbortSignal) => api<unknown>(`/expenses/${id}`, { signal }).then(z.object({ profile: expenseSchema }).parse).then(r=>r.profile);
export const createExpense = (data: unknown) => api<{profile: Expense}>("/expenses", { method: "POST", body: body(data) }).then(z.object({ profile: expenseSchema }).parse);
export const updateExpense = (id: string, data: unknown) => api<{profile: Expense}>(`/expenses/${id}`, { method: "PATCH", body: body(data) }).then(z.object({ profile: expenseSchema }).parse);
export const deleteExpense = (id: string) => api<unknown>(`/expenses/${id}`, { method: "DELETE" });
export const postExpense = (id: string) => api<{profile: Expense}>(`/expenses/${id}/post`, { method: "POST" }).then(z.object({ profile: expenseSchema }).parse);
export const cancelExpense = (id: string, reason: string) => api<{profile: Expense}>(`/expenses/${id}/cancel`, { method: "POST", body: body({ reason }) }).then(z.object({ profile: expenseSchema }).parse);
export const createTransfer = (data: unknown) => api<{profile: Transfer}>("/account-transfers", { method: "POST", body: body(data) }).then(z.object({ profile: transferSchema }).parse);
export const listTransfers = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/account-transfers?${q}`, { signal }).then(list(transferSchema).parse);
export const getTransfer = (id: string, signal?: AbortSignal) => api<unknown>(`/account-transfers/${id}`, { signal }).then(z.object({ profile: transferSchema }).parse).then(r=>r.profile);
export const reverseTransfer = (id: string, reason: string) => api<{profile: Transfer}>(`/account-transfers/${id}/reverse`, { method: "POST", body: body({ reason }) }).then(z.object({ profile: transferSchema }).parse);
export const listReceivables = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/receivables?${q}`, { signal }).then(list(settlementSchema).parse);
export const listPayables = (q = new URLSearchParams(), signal?: AbortSignal) => api<unknown>(`/payables?${q}`, { signal }).then(list(settlementSchema).parse);
