import { Test } from '@nestjs/testing';
import type { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { configureApp } from '../src/common/configure-app.js';
import { DatabaseService } from '../src/database/database.service.js';
import { TokenService } from '../src/auth/token.service.js';
import { Prisma } from '../src/generated/prisma/client.js';

const D = Prisma.Decimal;

describe('business documents HTTP (database double, real guards/services)', () => {
  let app: INestApplication, cookie: string;
  const user = { id: '11111111-1111-4111-8111-111111111111', currentBusinessId: '22222222-2222-4222-8222-222222222222', status: 'ACTIVE', authVersion: 0 };
  const documentId = '33333333-3333-4333-8333-333333333333';
  const productId = '44444444-4444-4444-8444-444444444444';
  const customerId = '55555555-5555-4555-8555-555555555555';
  const supplierId = '66666666-6666-4666-8666-666666666666';
  const business = { id: user.currentBusinessId, name: 'Legal Co', tradeName: 'Trade Co', gstRegistered: true, gstin: '27AAACB1234C1Z5', addressLine1: '1 Market', city: 'Pune', state: 'Maharashtra', stateCode: '27', pincode: '411001' };
  const customer = { id: customerId, businessId: user.currentBusinessId, customerCode: 'CUS-000001', displayName: 'Retail Buyer', businessName: null, gstRegistered: true, gstin: '27ABCDE1234F1Z5', pan: 'ABCDE1234F', phone: '9876543210', email: null, addressLine1: '2 Buyer Road', city: 'Pune', state: 'Maharashtra', stateCode: '27', pincode: '411001', isActive: true };
  const supplier = { id: supplierId, businessId: user.currentBusinessId, supplierCode: 'SUP-000001', displayName: 'Rice Supplier', businessName: null, gstRegistered: true, gstin: '29ABCDE1234F1Z5', pan: 'ABCDE1234F', phone: '9876543211', email: null, addressLine1: '3 Seller Road', city: 'Bengaluru', state: 'Karnataka', stateCode: '29', pincode: '560001', isActive: true };
  const product = { id: productId, businessId: user.currentBusinessId, productCode: 'PRD-000001', name: 'Rice', type: 'PRODUCT', hsnSacCode: '1006', unit: 'KG', gstRate: new D(5), salePrice: new D(100), purchasePrice: new D(80), trackInventory: true, currentStock: new D('10.000'), isActive: true };
  const purchaseBody = { supplierId, supplierInvoiceNumber: 'SUP-INV-1', placeOfSupplyState: 'Maharashtra', placeOfSupplyStateCode: '27', documentDate: '2026-09-08', priceMode: 'EXCLUSIVE', lines: [{ productId, quantity: '3.000', unitPrice: '80.00', discountType: 'NONE', discountValue: '0' }] };
  const db = {
    authSession: { findUnique: vi.fn() }, businessMember: { findUnique: vi.fn() }, business: { findFirstOrThrow: vi.fn(), findUniqueOrThrow: vi.fn() }, customer: { findFirst: vi.fn() }, supplier: { findFirst: vi.fn() }, product: { findMany: vi.fn(), updateMany: vi.fn() },
    businessDocument: { create: vi.fn(), findFirst: vi.fn(), findFirstOrThrow: vi.fn(), update: vi.fn(), updateMany: vi.fn(), delete: vi.fn(), findMany: vi.fn(), count: vi.fn() },
    businessDocumentLine: { deleteMany: vi.fn(), findMany: vi.fn() }, businessDocumentSequence: { upsert: vi.fn() }, stockMovement: { create: vi.fn() }, invoiceSequence: { upsert: vi.fn() }, invoiceLine: { deleteMany: vi.fn() },
    invoice: { findFirst: vi.fn(), create: vi.fn(), findFirstOrThrow: vi.fn(), updateMany: vi.fn(), update: vi.fn(), delete: vi.fn(), findMany: vi.fn(), count: vi.fn() }, $transaction: vi.fn(),
  };
  const docLine = (overrides: Record<string, unknown> = {}) => ({ id: 'line-a', documentId, businessId: user.currentBusinessId, productId, lineNumber: 1, sourceInvoiceLineId: null, sourceDocumentLineId: null, productCodeSnapshot: product.productCode, productNameSnapshot: product.name, productTypeSnapshot: 'PRODUCT', hsnSacCodeSnapshot: '1006', unitSnapshot: 'KG', quantity: new D('3.000'), unitPrice: new D('80'), priceMode: 'EXCLUSIVE', discountType: 'NONE', discountValue: new D('0'), discountAmount: new D('0'), grossAmount: new D('240'), taxableAmount: new D('240'), gstRate: new D('5'), cgstRate: new D('0'), cgstAmount: new D('0'), sgstRate: new D('0'), sgstAmount: new D('0'), igstRate: new D('5'), igstAmount: new D('12'), taxAmount: new D('12'), lineTotal: new D('252'), createdAt: new Date(), ...overrides });
  const doc = (overrides: Record<string, unknown> = {}) => ({
    id: documentId, businessId: user.currentBusinessId, documentType: 'PURCHASE_BILL', status: 'DRAFT', documentNumber: null, sequenceNumber: null, financialYear: '2026-27', documentDate: new Date('2026-09-08T00:00:00.000Z'), dueDate: null, validUntil: null, partyKind: 'supplier', customerId: null, supplierId, sourceInvoiceId: null, sourceDocumentId: null, supplierInvoiceNumber: 'SUP-INV-1', placeOfSupplyState: 'Maharashtra', placeOfSupplyStateCode: '27', gstApplicable: true, priceMode: 'EXCLUSIVE', reason: null, notes: null, terms: null,
    businessNameSnapshot: 'Trade Co', businessGstinSnapshot: business.gstin, businessAddressLine1: business.addressLine1, businessCity: business.city, businessState: business.state, businessStateCode: business.stateCode, businessPincode: business.pincode,
    partyCodeSnapshot: supplier.supplierCode, partyNameSnapshot: supplier.displayName, partyBusinessName: null, partyGstinSnapshot: supplier.gstin, partyPanSnapshot: supplier.pan, partyPhoneSnapshot: supplier.phone, partyEmailSnapshot: null, partyAddressLine1: supplier.addressLine1, partyCity: supplier.city, partyState: supplier.state, partyStateCode: supplier.stateCode, partyPincode: supplier.pincode,
    subtotal: new D('240'), discountTotal: new D('0'), taxableTotal: new D('240'), cgstTotal: new D('0'), sgstTotal: new D('0'), igstTotal: new D('12'), taxTotal: new D('12'), roundOff: new D('0'), grandTotal: new D('252'), actedAt: null, actedById: null, cancelledAt: null, cancelledById: null, cancellationReason: null, createdById: user.id, createdAt: new Date(), updatedAt: new Date(), lines: [docLine()], ...overrides,
  });
  const invoiceDraft = () => ({
    id: '88888888-8888-4888-8888-888888888888', businessId: user.currentBusinessId, status: 'DRAFT', invoiceNumber: null, sequenceNumber: null, financialYear: '2026-27', invoiceDate: new Date(), dueDate: null, customerId, placeOfSupplyState: 'Maharashtra', placeOfSupplyStateCode: '27', gstApplicable: true, priceMode: 'EXCLUSIVE', notes: null, terms: null,
    sellerBusinessName: 'Trade Co', sellerLegalName: 'Legal Co', sellerGstin: business.gstin, sellerPan: null, sellerAddressLine1: business.addressLine1, sellerAddressLine2: null, sellerCity: business.city, sellerState: business.state, sellerStateCode: business.stateCode, sellerPincode: business.pincode, sellerBankName: null, sellerAccountHolder: null, sellerAccountNumber: null, sellerIfsc: null, sellerUpiId: null,
    customerCodeSnapshot: customer.customerCode, customerNameSnapshot: customer.displayName, customerBusinessName: null, customerGstinSnapshot: customer.gstin, customerPanSnapshot: customer.pan, customerPhoneSnapshot: customer.phone, customerEmailSnapshot: null, billingAddressLine1: customer.addressLine1, billingAddressLine2: null, billingCity: customer.city, billingState: customer.state, billingStateCode: customer.stateCode, billingPincode: customer.pincode, shippingAddressLine1: null, shippingAddressLine2: null, shippingCity: null, shippingState: null, shippingStateCode: null, shippingPincode: null,
    subtotal: new D('200'), discountTotal: new D('0'), taxableTotal: new D('200'), cgstTotal: new D('5'), sgstTotal: new D('5'), igstTotal: new D('0'), taxTotal: new D('10'), roundOff: new D('0'), grandTotal: new D('210'), finalizedAt: null, finalizedById: null, cancelledAt: null, cancelledById: null, cancellationReason: null, createdById: user.id, createdAt: new Date(), updatedAt: new Date(),
    lines: [{ id: 'invoice-line-a', invoiceId: '88888888-8888-4888-8888-888888888888', businessId: user.currentBusinessId, productId, lineNumber: 1, productCodeSnapshot: product.productCode, productNameSnapshot: product.name, productTypeSnapshot: 'PRODUCT', hsnSacCodeSnapshot: '1006', unitSnapshot: 'KG', quantity: new D('2.000'), unitPrice: new D('100'), priceMode: 'EXCLUSIVE', discountType: 'NONE', discountValue: new D('0'), discountAmount: new D('0'), grossAmount: new D('200'), taxableAmount: new D('200'), gstRate: new D('5'), cgstRate: new D('2.5'), cgstAmount: new D('5'), sgstRate: new D('2.5'), sgstAmount: new D('5'), igstRate: new D('0'), igstAmount: new D('0'), taxAmount: new D('10'), lineTotal: new D('210'), createdAt: new Date() }],
  });
  beforeEach(async () => {
    vi.resetAllMocks(); let current = doc();
    db.$transaction.mockImplementation((fn) => fn(db)); db.authSession.findUnique.mockResolvedValue({ id: 'session-a', userId: user.id, user, expiresAt: new Date(Date.now() + 600000), revokedAt: null, authVersion: 0 }); db.businessMember.findUnique.mockResolvedValue({ role: 'OWNER' }); db.business.findFirstOrThrow.mockResolvedValue(business); db.business.findUniqueOrThrow.mockResolvedValue(business); db.customer.findFirst.mockResolvedValue(customer); db.supplier.findFirst.mockResolvedValue(supplier); db.product.findMany.mockResolvedValue([product]); db.product.updateMany.mockResolvedValue({ count: 1 }); db.businessDocumentSequence.upsert.mockResolvedValue({ nextNumber: 1 }); db.stockMovement.create.mockImplementation(({ data }) => data); db.businessDocumentLine.findMany.mockResolvedValue([]);
    db.businessDocument.create.mockImplementation(({ data }) => ({ ...doc({ documentType: data.documentType, status: 'DRAFT', documentNumber: null, sequenceNumber: null, ...data }), lines: data.lines.create.map((line: object) => ({ id: 'line-a', documentId, ...line })) })); db.businessDocument.findFirst.mockImplementation(() => Promise.resolve(current)); db.businessDocument.findFirstOrThrow.mockImplementation(() => Promise.resolve(current)); db.businessDocument.updateMany.mockImplementation(({ data, where }) => { if (where.status && current.status !== where.status) return { count: 0 }; current = { ...current, ...data }; return { count: 1 }; }); db.businessDocument.update.mockImplementation(({ data }) => ({ ...current, ...data, lines: data.lines.create.map((line: object) => ({ id: 'line-b', documentId, ...line })) })); db.businessDocument.findMany.mockResolvedValue([]); db.businessDocument.count.mockResolvedValue(0); db.businessDocument.delete.mockResolvedValue({});
    db.invoice.findFirst.mockResolvedValue({ id: '77777777-7777-4777-8777-777777777777', status: 'FINALIZED', lines: [{ id: 'inv-line-a', productId, productTypeSnapshot: 'PRODUCT', quantity: new D('2.000') }] }); db.invoice.create.mockImplementation(({ data }) => ({ ...invoiceDraft(), ...data, lines: data.lines.create.map((line: object) => ({ id: 'invoice-line-a', invoiceId: '88888888-8888-4888-8888-888888888888', ...line })) }));
    const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(DatabaseService).useValue(db).compile(); app = module.createNestApplication(); app.useLogger(false); configureApp(app); await app.init(); cookie = 'gst_access=' + await app.get(TokenService).sign(user.id, 'session-a');
  });
  afterEach(async () => app.close());
  const post = (path: string, payload: object = purchaseBody) => request(app.getHttpServer()).post('/api/v1' + path).set('Cookie', cookie).set('Origin', 'http://localhost:3000').set('X-CSRF-Protection', '1').send(payload);

  it('previews purchase bills with server totals and rejects client totals', async () => { const result = await post('/purchase-bills/preview').expect(201); expect(result.body.documentNumber).toBeNull(); expect(result.body.igstTotal).toBe('12.00'); await post('/purchase-bills/preview', { ...purchaseBody, grandTotal: '1.00' }).expect(400); });
  it('finalizes purchase bills with numbering, stock increase, and immutable snapshots', async () => { const result = await post('/purchase-bills/' + documentId + '/finalize', {}).expect(201); expect(result.body.profile.documentNumber).toBe('PB/2026-27/000001'); expect(db.product.updateMany.mock.calls[0]![0].data.currentStock.toFixed(3)).toBe('13.000'); expect(db.stockMovement.create.mock.calls[0]![0].data.type).toBe('PURCHASE_BILL_FINALIZED'); });
  it('cancels finalized purchase bills only when stock can be reversed', async () => { let finalized = doc({ status: 'FINALIZED', documentNumber: 'PB/2026-27/000001' }); db.businessDocument.findFirst.mockImplementation(() => Promise.resolve(finalized)); db.businessDocument.updateMany.mockResolvedValueOnce({ count: 1 }); await post('/purchase-bills/' + documentId + '/cancel', { reason: 'vendor correction' }).expect(201); expect(db.stockMovement.create.mock.calls[0]![0].data.type).toBe('PURCHASE_BILL_CANCELLED'); finalized = doc({ status: 'FINALIZED', documentNumber: 'PB/2026-27/000002' }); db.businessDocument.updateMany.mockResolvedValueOnce({ count: 1 }); db.product.findMany.mockResolvedValueOnce([{ ...product, currentStock: new D('1.000') }]); await post('/purchase-bills/' + documentId + '/cancel', { reason: 'vendor correction' }).expect(400); });
  it('supports non-stock sales document lifecycles and real conversions only', async () => { db.businessDocument.findFirst.mockResolvedValue(doc({ documentType: 'QUOTATION', partyKind: 'customer', customerId, supplierId: null, status: 'DRAFT', partyCodeSnapshot: customer.customerCode, partyNameSnapshot: customer.displayName, lines: [docLine({ quantity: new D('2.000'), unitPrice: new D('100') })] })); await post('/quotations/' + documentId + '/issue', {}).expect(201); expect(db.stockMovement.create).not.toHaveBeenCalled(); db.businessDocument.findFirst.mockResolvedValue(doc({ documentType: 'QUOTATION', partyKind: 'customer', customerId, supplierId: null, status: 'ISSUED', partyCodeSnapshot: customer.customerCode, partyNameSnapshot: customer.displayName })); const converted = await post('/quotations/' + documentId + '/convert/sales-order', {}).expect(201); expect(converted.body.profile.documentType).toBe('SALES_ORDER'); await post('/quotations/' + documentId + '/convert/invoice', {}).expect(400); });
  it('protects return quantities and aggregates tracked stock movement lines', async () => { db.businessDocument.findFirst.mockResolvedValue(doc({ documentType: 'SALES_RETURN', partyKind: 'customer', customerId, supplierId: null, sourceInvoiceId: '77777777-7777-4777-8777-777777777777', lines: [docLine({ id: 'r1', sourceInvoiceLineId: 'inv-line-a', quantity: new D('1.000') }), docLine({ id: 'r2', sourceInvoiceLineId: 'inv-line-a', quantity: new D('1.500') })] })); await post('/sales-returns/' + documentId + '/finalize', {}).expect(400); db.businessDocument.findFirst.mockResolvedValue(doc({ documentType: 'SALES_RETURN', partyKind: 'customer', customerId, supplierId: null, sourceInvoiceId: '77777777-7777-4777-8777-777777777777', lines: [docLine({ sourceInvoiceLineId: 'inv-line-a', quantity: new D('1.000') }), docLine({ id: 'r2', sourceInvoiceLineId: 'inv-line-a', quantity: new D('0.500') })] })); await post('/sales-returns/' + documentId + '/finalize', {}).expect(201); expect(db.product.updateMany.mock.calls.at(-1)![0].data.currentStock.toFixed(3)).toBe('11.500'); });
  it.each([['/quotations/', 'QUOTATION', 'ISSUED'], ['/sales-orders/', 'SALES_ORDER', 'CONFIRMED'], ['/delivery-challans/', 'DELIVERY_CHALLAN', 'ISSUED']])('converts %s to a fresh invoice draft without numbering or stock', async (path, documentType, status) => { db.businessDocument.findFirst.mockResolvedValue(doc({ documentType, status, partyKind: 'customer', customerId, supplierId: null, partyCodeSnapshot: customer.customerCode, partyNameSnapshot: customer.displayName, lines: [docLine({ quantity: new D('2.000'), unitPrice: new D('100') })] })); const result = await post(path + documentId + '/convert-to-invoice', {}).expect(201); expect(result.body.profile.status).toBe('DRAFT'); expect(result.body.profile.invoiceNumber).toBeNull(); expect(result.body.profile.customerNameSnapshot).toBe('Retail Buyer'); expect(db.invoice.create).toHaveBeenCalledTimes(1); expect(db.stockMovement.create).not.toHaveBeenCalled(); });
  it('rejects draft invoice conversion sources and non-sales document types', async () => { db.businessDocument.findFirst.mockResolvedValue(doc({ documentType: 'QUOTATION', status: 'DRAFT', partyKind: 'customer', customerId, supplierId: null })); await post('/quotations/' + documentId + '/convert-to-invoice', {}).expect(400); await post('/purchase-orders/' + documentId + '/convert-to-invoice', {}).expect(400); });
});