import { randomUUID } from 'node:crypto';
import { ConfigService } from '@nestjs/config';
import { DatabaseService } from '../src/database/database.service.js';
import { InventoryService } from '../src/catalogue/inventory.service.js';
import { ProductsService } from '../src/catalogue/products.service.js';
import { InvoiceCalculator } from '../src/invoices/invoice-calculator.js';
import { InvoicesService } from '../src/invoices/invoices.service.js';
import { FinanceService } from '../src/finance/finance.service.js';
import { PosService } from '../src/pos/pos.service.js';
import { safeUserSelect, type SafeUser } from '../src/users/user.select.js';

describe.skipIf(!process.env.TEST_DATABASE_URL)(
  'POS checkout (real PostgreSQL)',
  () => {
    let db: DatabaseService, pos: PosService;
    const businesses: string[] = [], users: string[] = [];
    beforeAll(async () => { const url = process.env.TEST_DATABASE_URL!; if (!new URL(url).pathname.endsWith('_test')) throw new Error('Use a dedicated *_test database'); db = new DatabaseService(new ConfigService({ DATABASE_URL: url })); const invoices = new InvoicesService(db, new InvoiceCalculator()); pos = new PosService(db, invoices, new FinanceService(db)); await db.$connect(); });
    afterAll(async () => { if (!db) return; await db.moneyAccountEntry.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.paymentAllocation.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.payment.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.stockMovement.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.invoiceLine.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.invoice.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.invoiceSequence.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.product.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.moneyAccount.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.businessMember.deleteMany({ where:{ businessId:{ in:businesses } } }); await db.user.deleteMany({ where:{ id:{ in:users } } }); await db.business.deleteMany({ where:{ id:{ in:businesses } } }); await db.$disconnect(); });
    async function owner(): Promise<SafeUser> { const user = await db.user.create({ data:{ email:randomUUID()+'@phase10.example', passwordHash:'test-only-not-a-login-hash', firstName:'POS', lastName:'Owner' } }); users.push(user.id); const business = await db.business.create({ data:{ name:'Phase 10 POS business', ownerName:'POS Owner', businessType:'PROPRIETORSHIP', gstRegistered:true, gstin:null, pan:null, mobile:'9876543210', email:user.email, addressLine1:'10 Counter Street', state:'Maharashtra', stateCode:'27', city:'Pune', pincode:'411001', invoicePrefix:'INV', financialYear:'2026-27', gstMode:'EXCLUSIVE', onboardingCompletedAt:new Date(), memberships:{ create:{ userId:user.id, role:'OWNER' } } } }); businesses.push(business.id); return db.user.update({ where:{ id:user.id }, data:{ currentBusinessId:business.id }, select:safeUserSelect }); }
    async function fixture(stock='1.000') { const user = await owner(); const products = new ProductsService(db, new InventoryService(db)); const product = await products.create(user, { name:'Counter Rice', type:'PRODUCT', unit:'KG', gstRate:'5.00', salePrice:'100.00', purchasePrice:'80.00', trackInventory:true, openingStock:stock, barcode:randomUUID().slice(0,12) }); const account = await new FinanceService(db).createAccount(user, { name:'Counter Cash', type:'CASH', openingBalance:'0.00' }) as any; return { user, product, account }; }
    const dto = (productId:string, id=randomUUID(), accountId?:string) => ({ clientCheckoutId:id, customerMode:'WALK_IN' as const, placeOfSupplyState:'Maharashtra', placeOfSupplyStateCode:'27', invoiceDate:'2026-09-11', priceMode:'EXCLUSIVE' as const, paymentMode:accountId?'RECORDED_PAYMENT' as const:'PAY_LATER' as const, tender:accountId?{ accountId, method:'CASH' as const, amount:'105.00', tenderedAmount:'110.00' }:undefined, lines:[{ productId, quantity:'1.000', unitPrice:'100.00', discountType:'NONE' as const }] });
    it('prevents two POS checkouts from selling the same last tracked stock', async () => { const f = await fixture(); const results = await Promise.allSettled([pos.checkout(f.user, dto(f.product.id)), pos.checkout(f.user, dto(f.product.id))]); expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1); expect(await db.invoice.count({ where:{ businessId:f.user.currentBusinessId!, salesChannel:'POS', status:'FINALIZED' } })).toBe(1); });
    it('reuses the same invoice for a repeated POS clientCheckoutId and records retained cash only', async () => { const f = await fixture('2.000'); const key = randomUUID(); const first:any = await pos.checkout(f.user, dto(f.product.id, key, f.account.id)); const second:any = await pos.checkout(f.user, dto(f.product.id, key, f.account.id)); expect(second.duplicate).toBe(true); expect(second.invoice.id).toBe(first.invoice.id); expect(first.changeDue).toBe('5.00'); expect(await db.invoice.count({ where:{ businessId:f.user.currentBusinessId!, posClientCheckoutId:key } })).toBe(1); expect((await db.moneyAccount.findFirstOrThrow({ where:{ id:f.account.id } })).currentBalance.toFixed(2)).toBe('105.00'); });
  },
);
