import { Test } from '@nestjs/testing';
import type { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { configureApp } from '../src/common/configure-app.js';
import { DatabaseService } from '../src/database/database.service.js';
import { TokenService } from '../src/auth/token.service.js';
import { InvoicesService } from '../src/invoices/invoices.service.js';
import { FinanceService } from '../src/finance/finance.service.js';
import { Prisma } from '@gst/prisma-client/client';

const D = Prisma.Decimal;
const user = { id: '11111111-1111-4111-8111-111111111111', currentBusinessId: '22222222-2222-4222-8222-222222222222', status: 'ACTIVE', authVersion: 0 };
const product = { id:'33333333-3333-4333-8333-333333333333', productCode:'PRD-000001', name:'Retail Rice', type:'PRODUCT', unit:'KG', sku:'RICE', barcode:'8901', salePrice:new D('100.00'), gstRate:new D('5.00'), currentStock:new D('2.000'), minimumStock:new D('3.000'), trackInventory:true };
const invoice = { id:'44444444-4444-4444-8444-444444444444', status:'FINALIZED', invoiceNumber:'INV/2026-27/000001', salesChannel:'POS', customerId:null, customerNameSnapshot:'Walk-in Customer', invoiceDate:'2026-09-11', placeOfSupplyState:'Maharashtra', placeOfSupplyStateCode:'27', priceMode:'EXCLUSIVE', taxableTotal:'100.00', cgstTotal:'2.50', sgstTotal:'2.50', igstTotal:'0.00', taxTotal:'5.00', grandTotal:'105.00', lines:[], settlement:{ paymentStatus:'UNPAID', paidAmount:'0.00', outstanding:'105.00', paymentHistory:[] } };

describe('POS HTTP (database double, real guards/controllers)', () => {
  let app: INestApplication, cookie: string;
  const db = { authSession:{findUnique:vi.fn()}, businessMember:{findUnique:vi.fn()}, product:{findMany:vi.fn(),count:vi.fn(),findFirst:vi.fn()}, invoice:{findFirst:vi.fn(),findMany:vi.fn(),count:vi.fn()}, $transaction:vi.fn() };
  const invoices = { previewPos:vi.fn(), createFinalizedPosInvoice:vi.fn(), detail:vi.fn() };
  const finance = { createPayment:vi.fn(), postPayment:vi.fn() };
  beforeEach(async()=>{ vi.resetAllMocks(); db.$transaction.mockImplementation((arg:any)=>Array.isArray(arg)?Promise.all(arg):arg(db)); db.authSession.findUnique.mockResolvedValue({ id:'session-a', userId:user.id, user, expiresAt:new Date(Date.now()+600000), revokedAt:null, authVersion:0 }); db.businessMember.findUnique.mockResolvedValue({ role:'OWNER' }); db.product.findMany.mockResolvedValue([product]); db.product.count.mockResolvedValue(1); db.product.findFirst.mockResolvedValue(product); db.invoice.findFirst.mockResolvedValue(null); db.invoice.findMany.mockResolvedValue([{...invoice, invoiceDate:new Date('2026-09-11T00:00:00.000Z'), grandTotal:new D('105.00'), lines:[{id:'line'}], paymentAllocations:[]}]); db.invoice.count.mockResolvedValue(1); invoices.previewPos.mockResolvedValue(invoice); invoices.createFinalizedPosInvoice.mockResolvedValue(invoice); invoices.detail.mockResolvedValue({...invoice, settlement:{ paymentStatus:'PAID', paidAmount:'105.00', outstanding:'0.00', paymentHistory:[] }}); finance.createPayment.mockResolvedValue({ id:'pay-1' }); finance.postPayment.mockResolvedValue({ id:'pay-1', status:'POSTED', method:'CASH' }); const module=await Test.createTestingModule({imports:[AppModule]}).overrideProvider(DatabaseService).useValue(db).overrideProvider(InvoicesService).useValue(invoices).overrideProvider(FinanceService).useValue(finance).compile(); app=module.createNestApplication(); app.useLogger(false); configureApp(app); await app.init(); cookie='gst_access='+await app.get(TokenService).sign(user.id,'session-a'); });
  afterEach(async()=>{ if(app) await app.close(); });
  const get=(p:string)=>request(app.getHttpServer()).get('/api/v1'+p).set('Cookie',cookie); const post=(p:string,b:any)=>request(app.getHttpServer()).post('/api/v1'+p).set('Cookie',cookie).set('Origin','http://localhost:3000').set('X-CSRF-Protection','1').send(b);
  const body={clientCheckoutId:'55555555-5555-4555-8555-555555555555',customerMode:'WALK_IN',placeOfSupplyState:'Maharashtra',placeOfSupplyStateCode:'27',invoiceDate:'2026-09-11',priceMode:'EXCLUSIVE',paymentMode:'PAY_LATER',lines:[{productId:product.id,quantity:'1.000',unitPrice:'100.00',discountType:'NONE'}]};
  it('serves bounded active product lookup and exact barcode lookup', async()=>{ const list=await get('/pos/products?search=rice&pageSize=5').expect(200); expect(list.body.items[0].stockStatus).toBe('LOW_STOCK'); expect(db.product.findMany.mock.calls[0]![0]).toMatchObject({take:5}); expect(db.product.findMany.mock.calls[0]![0].where).toMatchObject({businessId:user.currentBusinessId,isActive:true}); const found=await get('/pos/products/by-barcode/8901').expect(200); expect(found.body.profile.code).toBe('PRD-000001'); expect(db.product.findFirst.mock.calls[0]![0].where).toMatchObject({businessId:user.currentBusinessId,barcode:'8901',isActive:true}); });
  it('previews walk-in POS sales through invoice preview without client totals', async()=>{ await post('/pos/preview',body).expect(201); expect(invoices.previewPos).toHaveBeenCalledWith(expect.objectContaining({id:user.id}), expect.objectContaining({customerId:undefined, lines:expect.any(Array)})); });
  it('finalizes a normal POS invoice with Pay Later and idempotency key', async()=>{ const res=await post('/pos/checkout',body).expect(201); expect(res.body.invoice.salesChannel).toBe('POS'); expect(res.body.payment).toBeNull(); expect(invoices.createFinalizedPosInvoice).toHaveBeenCalledWith(expect.anything(), expect.anything(), body.clientCheckoutId); });
  it('records full payment after invoice finalization and caps change due', async()=>{ const paid={...body,paymentMode:'RECORDED_PAYMENT',tender:{accountId:'66666666-6666-4666-8666-666666666666',method:'CASH',amount:'105.00',tenderedAmount:'110.00'}}; const res=await post('/pos/checkout',paid).expect(201); expect(res.body.changeDue).toBe('5.00'); expect(finance.createPayment).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({type:'CUSTOMER_RECEIPT',amount:'105.00',allocations:[{invoiceId:invoice.id,amount:'105.00'}]})); expect(finance.postPayment).toHaveBeenCalledWith(expect.anything(),'pay-1'); });
  it('lists finalized POS sales only with derived payment state', async()=>{ const res=await get('/pos/sales?page=1&pageSize=10').expect(200); expect(res.body.items[0]).toMatchObject({salesChannel:'POS',paymentStatus:'UNPAID'}); expect(db.invoice.findMany.mock.calls[0]![0].where).toMatchObject({businessId:user.currentBusinessId,salesChannel:'POS',status:'FINALIZED'}); });
  it('rejects client-controlled businessId and authoritative totals', async()=>{ await get('/pos/products?businessId='+user.currentBusinessId).expect(400); await post('/pos/checkout',{...body,grandTotal:'1.00'}).expect(400); });
});
